//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import ___PROJECTNAME___
import XCTest

class ___FILEBASENAMEASIDENTIFIER___InteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: ___FILEBASENAMEASIDENTIFIER___Interactor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setup___FILEBASENAMEASIDENTIFIER___Interactor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setup___FILEBASENAMEASIDENTIFIER___Interactor()
  {
    sut = ___FILEBASENAMEASIDENTIFIER___Interactor()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testSomething()
  {
    // Given
    
    // When
    
    // Then
  }
}
