//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import ___PROJECTNAME___
import XCTest

import Quick
import Nimble

class ___FILEBASENAMEASIDENTIFIER___WorkerTests: QuickSpec {
    
    var sut: ___FILEBASENAMEASIDENTIFIER___Worker!
    
    override func spec() {
        beforeEach {
            sut = ___FILEBASENAMEASIDENTIFIER___Worker()
        }
    }
}
