//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import ___PROJECTNAME___
import XCTest

import Quick
import Nimble

class ___FILEBASENAMEASIDENTIFIER___ViewControllerTests: QuickSpec {
    // MARK: Subject under test
    
    var sut: ___FILEBASENAMEASIDENTIFIER___ViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func spec() {
        beforeEach {
            window = UIWindow()
            let bundle = Bundle.main
            let storyboard = UIStoryboard(name: "Main", bundle: bundle)
            sut = storyboard.instantiateViewController(withIdentifier: ___FILEBASENAMEASIDENTIFIER___ViewController.identifier) as! ___FILEBASENAMEASIDENTIFIER___ViewController
            
            window.addSubview(sut.view)
            RunLoop.current.run(until: Date())
        }
        
        afterEach {
            window = nil
        }
    }
}
