//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

class ___FILEBASENAMEASIDENTIFIER___Worker {
    // MARK: Business Logic
    
    func doSomeWork() {
        // NOTE: Do the work
    }
}
