//
//  UserStore.swift
//  Example
//
//  Created by Joel on 05/04/2017.
//  Copyright (c) 2017 HELM S.C.P. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

protocol UserStore {
    func getUser(completion: @escaping UserStoreGetUserCompletionHandler)
}

typealias UserStoreGetUserCompletionHandler = (UserStoreResult<User>) -> Void

enum UserStoreResult<U> {
    case success(result: U)
    case failure(error: UserStoreError)
}

enum UserStoreEmptyResult {
    case success
    case failure(error: UserStoreError)
}

enum UserStoreError: Equatable, Error {
    case cannotGet(String)
}

func ==(lhs: UserStoreError, rhs: UserStoreError) -> Bool {
    switch (lhs, rhs) {
    case (.cannotGet(let a), .cannotGet(let b)) where a == b: return true
    default:
        return false
    }
}
