//
//  UserDetailViewController.swift
//  Example
//
//  Created by Joel on 05/04/2017.
//  Copyright (c) 2017 HELM S.C.P. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol UserDetailViewControllerInput {
    func displayUser(viewModel: UserDetailScene.GetUser.ViewModel)
}

protocol UserDetailViewControllerOutput {
    func getUser(request: UserDetailScene.GetUser.Request)
}

class UserDetailViewController: UIViewController, UserDetailViewControllerInput {
    
    var output: UserDetailViewControllerOutput?
    var router: UserDetailRouter?
    
    @IBOutlet weak var userImage: UIImageView!
    @IBOutlet weak var userDataTableView: UITableView!
    
    var atributes: [UserDetailScene.GetUser.ViewModel.Atribute] = []
    
    // MARK: Object lifecycle
    
    override func awakeFromNib() {
        super.awakeFromNib()
        UserDetailConfigurator.sharedInstance.configure(viewController: self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        getUser()
    }
    
    // MARK: Requests
    
    func getUser() {
        let request = UserDetailScene.GetUser.Request()
        output?.getUser(request: request)
    }
    
    // MARK: Display logic
    
    func displayUser(viewModel: UserDetailScene.GetUser.ViewModel) {
        
        if let url = URL(string: viewModel.imagePath) {
            self.userImage.kf.setImage(with: url)
        }
        
        atributes = viewModel.atributes
        userDataTableView.reloadData()
    }

    
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension UserDetailViewController: UserDetailPresenterOutput {
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router?.passDataToNextScene(for: segue)
    }
}
