//
//  UserDetailRouter.swift
//  Example
//
//  Created by Joel on 05/04/2017.
//  Copyright (c) 2017 HELM S.C.P. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol UserDetailRouterInput {
    
}

protocol UserDetailRouterDataSource: class {
    
}

protocol UserDetailRouterDataDestination: class {
    var user: User! { get set }
}

class UserDetailRouter: UserDetailRouterInput {
    
    weak var viewController: UserDetailViewController!
    weak private var dataSource: UserDetailRouterDataSource!
    weak var dataDestination: UserDetailRouterDataDestination!
    
    init(viewController: UserDetailViewController, dataSource: UserDetailRouterDataSource, dataDestination: UserDetailRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
