//
//  UserDetailConfigurator.swift
//  Example
//
//  Created by Joel on 05/04/2017.
//  Copyright (c) 2017 HELM S.C.P. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension UserDetailInteractor: UserDetailViewControllerOutput, UserDetailRouterDataSource, UserDetailRouterDataDestination {
}

extension UserDetailPresenter: UserDetailInteractorOutput {
}

class UserDetailConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = UserDetailConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: UserDetailViewController) {
        
        let presenter = UserDetailPresenter()
        presenter.output = viewController
        
        let interactor = UserDetailInteractor()
        interactor.output = presenter
        
        let router = UserDetailRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
