//
//  UserDetailModels.swift
//  Example
//
//  Created by Miguel Berrocal Gómez on 14/04/16.
//  Copyright (c) 2016 HELM S.C.P. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//
//  Type "usecase" for some magic!

import UIKit



struct UserDetail {
    struct GetUser {
        
        struct Request {
            
        }
        
        struct Response {
            let user:User
        }
        
        struct ViewModel {
            let user:ViewModel.User
            
            struct User {
                let attributes:[UserDetail.ViewModel.Attribute]
                let imageURLString:String
            }
        }
    }
    
    struct ViewModel {
        struct Attribute {
            let title:String
            let value:String
        }
    }
}
