//
//  UserDetailModels.swift
//  Example
//
//  Created by Joel on 05/04/2017.
//  Copyright (c) 2017 HELM S.C.P. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//
//  Type "usecase" for some magic!

struct UserDetailScene {
    
    struct GetUser {
        
        struct Request {
            
        }
        
        struct Response {
            var user: User
        }
        
        struct ViewModel {
            let imagePath: String
            let atributes: [Atribute]
            
            struct Atribute {
                let title: String
                let value: String
            }
        }
    }
}
