//
//  UserDetailInteractor.swift
//  Example
//
//  Created by Joel on 05/04/2017.
//  Copyright (c) 2017 HELM S.C.P. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

protocol UserDetailInteractorInput {
    func getUser(request: UserDetailScene.GetUser.Request)
}

protocol UserDetailInteractorOutput {
    func presentUser(response: UserDetailScene.GetUser.Response)
}

protocol UserDetailDataSource {
    
}

protocol UserDetailDataDestination {
    var user: User! { get set }
}

class UserDetailInteractor: UserDetailInteractorInput, UserDetailDataSource, UserDetailDataDestination {
    
    var output: UserDetailInteractorOutput?
    
    var user: User!
    
    // MARK: Business logic
    
    func getUser(request: UserDetailScene.GetUser.Request) {
        
        // NOTE: Pass the result to the Presenter
        
        let response = UserDetailScene.GetUser.Response(user: user)
        output?.presentUser(response: response)
    }
}
