//
//  UserDetailConfigurator.swift
//  Example
//
//  Created by Miguel Berrocal Gómez on 14/04/16.
//  Copyright (c) 2016 HELM S.C.P. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension UserDetailInteractor: UserDetailViewControllerOutput, UserDetailRouterDataSource, UserDetailRouterDataDestination {
}

extension UserDetailPresenter: UserDetailInteractorOutput {
}

class UserDetailConfigurator {
    // MARK: Object lifecycle
    
    class var sharedInstance: UserDetailConfigurator {
        struct Static {
            static var instance: UserDetailConfigurator?
            static var token: dispatch_once_t = 0
        }
        
        dispatch_once(&Static.token) {
            Static.instance = UserDetailConfigurator()
        }
        
        return Static.instance!
    }
    
    // MARK: Configuration
    
    func configure(viewController: UserDetailViewController) {
        
        let presenter = UserDetailPresenter()
        presenter.output = viewController
        
        let interactor = UserDetailInteractor()
        interactor.output = presenter
        
        let router = UserDetailRouter(viewController:viewController, dataSource:interactor, dataDestination:interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
