//
//  UserDetailInteractor.swift
//  Example
//
//  Created by Miguel Berrocal Gómez on 14/04/16.
//  Copyright (c) 2016 HELM S.C.P. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol UserDetailInteractorInput {
    func getUser(request:UserDetail.GetUser.Request)
}

protocol UserDetailInteractorOutput {
    func presentUser(response:UserDetail.GetUser.Response)
}

protocol UserDetailDataSource {

}

protocol UserDetailDataDestination {
    var user:User! {get set}
}

class UserDetailInteractor: UserDetailInteractorInput, UserDetailDataSource, UserDetailDataDestination {
    
    var output: UserDetailInteractorOutput!
    
    var user:User!
    
    // MARK: Business logic
    func getUser(request:UserDetail.GetUser.Request) {
        let response = UserDetail.GetUser.Response(user: user)
        output.presentUser(response)
    }

}
