//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol ___VARIABLE_sceneName___InteractorInput {
    
}

protocol ___VARIABLE_sceneName___InteractorOutput {
    
}

protocol ___VARIABLE_sceneName___DataSource {
    
}

protocol ___VARIABLE_sceneName___DataDestination {
    
}

class ___VARIABLE_sceneName___Interactor: ___VARIABLE_sceneName___InteractorInput, ___VARIABLE_sceneName___DataSource, ___VARIABLE_sceneName___DataDestination {
    
    var output: ___VARIABLE_sceneName___InteractorOutput?
    
    // MARK: Business logic
    

}
