//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension ___VARIABLE_sceneName___Interactor: ___VARIABLE_sceneName___ViewControllerOutput, ___VARIABLE_sceneName___RouterDataSource, ___VARIABLE_sceneName___RouterDataDestination {
}

extension ___VARIABLE_sceneName___Presenter: ___VARIABLE_sceneName___InteractorOutput {
}

class ___VARIABLE_sceneName___Configurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = ___VARIABLE_sceneName___Configurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: ___VARIABLE_sceneName___ViewController) {
        
        let presenter = ___VARIABLE_sceneName___Presenter()
        presenter.output = viewController
        
        let interactor = ___VARIABLE_sceneName___Interactor()
        interactor.output = presenter
        
        let router = ___VARIABLE_sceneName___Router(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
