//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

import UIKit

protocol ___VARIABLE_sceneName___RouterInput {
    
}

protocol ___VARIABLE_sceneName___RouterDataSource: class {
    
}

protocol ___VARIABLE_sceneName___RouterDataDestination: class {
    
}

class ___VARIABLE_sceneName___Router: ___VARIABLE_sceneName___RouterInput {
    
    weak var viewController: ___VARIABLE_sceneName___ViewController!
    weak private var dataSource: ___VARIABLE_sceneName___RouterDataSource!
    weak var dataDestination: ___VARIABLE_sceneName___RouterDataDestination!
    
    init(viewController: ___VARIABLE_sceneName___ViewController, dataSource: ___VARIABLE_sceneName___RouterDataSource, dataDestination: ___VARIABLE_sceneName___RouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    
    // MARK: Communication
    
    func passDataToNextScene(for segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        
    }
}
