//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol ___VARIABLE_sceneName___PresenterInput {
    
}

protocol ___VARIABLE_sceneName___PresenterOutput: class {
    
}

class ___VARIABLE_sceneName___Presenter: ___VARIABLE_sceneName___PresenterInput {
    
    weak var output: ___VARIABLE_sceneName___PresenterOutput?
    
    // MARK: Presentation logic
    
}
