//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol ___FILEBASENAMEASIDENTIFIER___InteractorInput {
    
}

protocol ___FILEBASENAMEASIDENTIFIER___InteractorOutput {
    
}

protocol ___FILEBASENAMEASIDENTIFIER___DataSource {
    
}

protocol ___FILEBASENAMEASIDENTIFIER___DataDestination {
    
}

class ___FILEBASENAMEASIDENTIFIER___Interactor: ___FILEBASENAMEASIDENTIFIER___InteractorInput, ___FILEBASENAMEASIDENTIFIER___DataSource, ___FILEBASENAMEASIDENTIFIER___DataDestination {
    
    var output: ___FILEBASENAMEASIDENTIFIER___InteractorOutput?
    
    // MARK: Business logic
    

}
