//
//  UserListPresenter.swift
//  Example
//
//  Created by Joel on 05/04/2017.
//  Copyright (c) 2017 HELM S.C.P. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

protocol UserListPresenterInput {
    func presentUser(response: UserListScene.GetUser.Response)
}

protocol UserListPresenterOutput: class {
    func displayUser(viewModel: UserListScene.GetUser.ViewModel)
}

class UserListPresenter: UserListPresenterInput {
    
    weak var output: UserListPresenterOutput?
    
    // MARK: Presentation logic
    
    func presentUser(response: UserListScene.GetUser.Response)
    {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        
        let user = response.newUser
        
        let userNameData = user.name
        let userName = userNameData.title.capitalized + ". " + userNameData.firstName.capitalized + " " + userNameData.lastName.capitalized
        
        let userViewModel = UserListScene.GetUser.ViewModel.User(name: userName, email: user.email, imagePath: user.thumbImagePath)
        
        let viewModel = UserListScene.GetUser.ViewModel(user: userViewModel)
        
        output?.displayUser(viewModel: viewModel)
    }
    
}
