//
//  UserListRouter.swift
//  Example
//
//  Created by Miguel Berrocal Gómez on 14/04/16.
//  Copyright (c) 2016 HELM S.C.P. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol UserListRouterInput {
    func navigateToUserDetailScene()
}

protocol UserListRouterDataSource:class {
    var selectedUser:User! { get }
}

protocol UserListRouterDataDestination:class {
    
}

class UserListRouter: UserListRouterInput {
    
    weak var viewController:UserListViewController!
    weak private var dataSource:UserListRouterDataSource!
    weak var dataDestination:UserListRouterDataDestination!
    
    struct SegueIdentifiers {
        static let userDetail = "ShowUserDetailScene"
    }
    
    init(viewController:UserListViewController, dataSource:UserListRouterDataSource, dataDestination:UserListRouterDataDestination) {
        self.viewController = viewController
        self.dataSource = dataSource
        self.dataDestination = dataDestination
    }
    
    // MARK: Navigation
    func navigateToUserDetailScene() {
        viewController.performSegueWithIdentifier(SegueIdentifiers.userDetail, sender: viewController)
    }

    // MARK: Communication
    
    func passDataToNextScene(segue: UIStoryboardSegue) {
        // NOTE: Teach the router which scenes it can communicate with
        guard let segueIdentifier = segue.identifier else {
            return
        }
        
        switch segueIdentifier {
        case SegueIdentifiers.userDetail:
            passDataToUserDetailScene(segue)
        default:
            return
        }
    }
    
    func passDataToUserDetailScene(segue:UIStoryboardSegue) {
        if let userDetailViewController = segue.destinationViewController as? UserDetailViewController {
            userDetailViewController.router.dataDestination.user = dataSource.selectedUser
        }
    }
}
