//
//  UserListConfigurator.swift
//  Example
//
//  Created by Joel on 05/04/2017.
//  Copyright (c) 2017 HELM S.C.P. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension UserListInteractor: UserListViewControllerOutput, UserListRouterDataSource, UserListRouterDataDestination {
}

extension UserListPresenter: UserListInteractorOutput {
}

class UserListConfigurator {
    // MARK: Object lifecycle
    
    static let sharedInstance = UserListConfigurator()
    
    private init() {}
    
    // MARK: Configuration
    
    func configure(viewController: UserListViewController) {
        
        let presenter = UserListPresenter()
        presenter.output = viewController
        
        let interactor = UserListInteractor()
        interactor.output = presenter
        
        let router = UserListRouter(viewController: viewController, dataSource: interactor, dataDestination: interactor)
        
        viewController.output = interactor
        viewController.router = router
    }
}
