//
//  UserListModels.swift
//  Example
//
//  Created by Joel on 05/04/2017.
//  Copyright (c) 2017 HELM S.C.P. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//
//  Type "usecase" for some magic!

struct UserListScene {
    
    struct GetUser {
        
        struct Request {
        
        }
        
        struct Response {
            var newUser: User
        }
        
        struct ViewModel {
            let user: User
            
            struct User {
                let name: String
                let email: String
                let imagePath: String
            }
        }
    }
    
    struct SelectUser {
        
        struct Request {
            let index:Int
        }
    }
    
}
