//
//  UserListPresenter.swift
//  Example
//
//  Created by Miguel Berrocal Gómez on 14/04/16.
//  Copyright (c) 2016 HELM S.C.P. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol UserListPresenterInput {
    func presentUser(response:UserList.GetUser.Response)
}

protocol UserListPresenterOutput: class {
    func displayUser(viewModel:UserList.GetUser.ViewModel)
}

class UserListPresenter: UserListPresenterInput {
    
    weak var output: UserListPresenterOutput!
    
    // MARK: Presentation logic
    
    func presentUser(response:UserList.GetUser.Response) {
        let viewModel = mapGetUserResponseToViewModel(response)
        output.displayUser(viewModel)
    }
    
    private func mapGetUserResponseToViewModel(response:UserList.GetUser.Response) -> UserList.GetUser.ViewModel {
        let user = response.user
        let viewModelUser = UserList.ViewModel.User(name: user.name.fullName(), imageURLString: user.imageURLString)
        return UserList.GetUser.ViewModel(user: viewModelUser)
    }
    
}
