//
//  UserListWorker.swift
//  Example
//
//  Created by Joel on 05/04/2017.
//  Copyright (c) 2017 HELM S.C.P. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

class UserListWorker {
    // MARK: Business Logic
    
    let store: UserStore
    
    init(store: UserStore) {
        self.store = store
    }
    
    func getUser(completionHandler: @escaping (UserStoreResult<User>) -> Void){
        store.getUser(completion: completionHandler)
    }
}
