//
//  UserListViewController.swift
//  Example
//
//  Created by Miguel Berrocal Gómez on 14/04/16.
//  Copyright (c) 2016 HELM S.C.P. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

protocol UserListViewControllerInput {
    func displayUser(viewModel:UserList.GetUser.ViewModel)
}

protocol UserListViewControllerOutput {
    func getUser(request:UserList.GetUser.Request)
    func selectUser(request:UserList.SelectUser.Request)
}

class UserListViewController: UIViewController, UserListViewControllerInput {
    
    var output: UserListViewControllerOutput!
    var router: UserListRouter!
    var users:[UserList.ViewModel.User] = []
    
    @IBOutlet weak var userListTableView: UITableView!
    // MARK: Object lifecycle
    
    struct cellIdentifiers {
        static let userCell = "userCell"
    }
    
    override func awakeFromNib() {
        super.awakeFromNib()
        UserListConfigurator.sharedInstance.configure(self)
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        configureTableViewOnLoad()
    }
    
    // MARK: Event handling
    
    @IBAction func addUserButtonItemTapped(sender: UIBarButtonItem) {
        addUser()
    }
    
    func addUser() {
        let request = UserList.GetUser.Request()
        output.getUser(request)
    }
    
    func selectedUserAtIndex(index:Int) {
        let request = UserList.SelectUser.Request(index: index)
        output.selectUser(request)
        router.navigateToUserDetailScene()
    }
    
    func configureTableViewOnLoad() {
        userListTableView.registerNib(UINib(nibName: "UserTableViewCell", bundle: NSBundle.mainBundle()), forCellReuseIdentifier: cellIdentifiers.userCell)
    }
    
    // MARK: Display logic
    func displayUser(viewModel:UserList.GetUser.ViewModel) {
        users.insert(viewModel.user, atIndex: 0)
        userListTableView.insertRowsAtIndexPaths([NSIndexPath(forRow: users.startIndex, inSection: 0)], withRowAnimation: .Top)
    }
}

//This should be on configurator but for some reason storyboard doesn't detect ViewController's name if placed there
extension UserListViewController: UserListPresenterOutput {
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        router.passDataToNextScene(segue)
    }
}