//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//  https://github.com/HelmMobile/clean-swift-templates

protocol ___FILEBASENAMEASIDENTIFIER___PresenterInput {
    
}

protocol ___FILEBASENAMEASIDENTIFIER___PresenterOutput: class {
    
}

class ___FILEBASENAMEASIDENTIFIER___Presenter: ___FILEBASENAMEASIDENTIFIER___PresenterInput {
    
    weak var output: ___FILEBASENAMEASIDENTIFIER___PresenterOutput?
    
    // MARK: Presentation logic
    
}
